# Generated by Django 3.0.5 on 2020-04-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='picture',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
