# Generated by Django 3.0.5 on 2020-04-30 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0002_productdb_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdb',
            name='picture',
        ),
    ]
